name: raisetheaverage
favicon: null
layout_spectrum: 0.6246424550190568
typography_spectrum: 0.15827915887348354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6746554295532405
  lightness: 0.020894527668133378
  saturation: 0.8193783715832978
  rhythmicContrast: 0.1829301028046757
purpose: []
